# MySQL con XAMPP (configuración típica)
spring.datasource.url=jdbc:mysql://localhost:3306/bbdd_curso_apis?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true